# Generated by Django 3.1.3 on 2020-11-11 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20201111_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_bought', models.DateField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('expended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=200)),
                ('last_restock_length', models.IntegerField(max_length=4)),
                ('purchase_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.material')),
            ],
        ),
    ]
