# Generated by Django 3.1.3 on 2020-11-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_color_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='last_restock_length',
            field=models.IntegerField(),
        ),
    ]
