# Generated by Django 3.1.3 on 2020-11-11 14:04

from django.db import migrations, models
import django.db.models.deletion
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_customer_productcolorslot_storeproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='normal_wrist_size',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StoreSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField()),
                ('product_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.storeproduct')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.sale')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=management.models.Product, to='management.customer'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.customer')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.sale')),
            ],
        ),
    ]
