# Generated by Django 3.1.3 on 2020-11-12 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20201111_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='ItemColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=200)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.color')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrist_size', models.IntegerField()),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.product')),
                ('builder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.order')),
            ],
        ),
    ]
