# Generated by Django 3.1.3 on 2020-11-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_item_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
