# Generated by Django 3.1.3 on 2020-11-12 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20201112_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='wrist_size',
            new_name='size',
        ),
    ]
