# Generated by Django 3.1.3 on 2020-11-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20201112_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='last_restock_length',
            new_name='estimated_length',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sale',
        ),
        migrations.AddField(
            model_name='sale',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
