# Generated by Django 3.1.3 on 2020-11-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20201118_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='builder',
        ),
        migrations.AddField(
            model_name='employee',
            name='amount_owed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
