# Generated by Django 3.1.3 on 2020-11-26 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20201126_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='builder',
        ),
        migrations.CreateModel(
            name='EmployeeBuilds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=True)),
                ('color_description', models.TextField()),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.employee')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.product')),
            ],
        ),
    ]
