# Generated by Django 3.1.3 on 2020-11-26 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_auto_20201126_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeebuilds',
            old_name='color_description',
            new_name='description',
        ),
    ]
