# Generated by Django 3.1.3 on 2020-11-26 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20201126_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebuilds',
            name='date_completed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
