# Generated by Django 3.1.3 on 2020-11-26 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_employeebuilds_date_completed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeBuilds',
            new_name='EmployeeBuild',
        ),
    ]
