# Generated by Django 3.1.3 on 2020-11-29 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_auto_20201129_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.sale'),
        ),
    ]
