# Generated by Django 3.1.3 on 2020-11-30 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_auto_20201129_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='description',
            new_name='notes',
        ),
    ]
